name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        # https://github.com/actions/virtual-environments/tree/main/images/linux
        # Ubuntu 20.04 entries use pipewire-0.2
        #- { os: "ubuntu-20.04", cc: "gcc-10",   cxx: "g++-10",   pipewire: "libpipewire-0.2-dev" }
        #- { os: "ubuntu-20.04", cc: "clang-12", cxx: "clang++-12", pipewire: "libpipewire-0.2-dev" }
        # Ubuntu 22.04 entries use pipewire-0.3
        - { os: "ubuntu-22.04", cc: "gcc-12",   cxx: "g++-12" }
        - { os: "ubuntu-22.04", cc: "clang-15", cxx: "clang++-15" }
        
        # Ubuntu 24.04 entries use pipewire-0.3
        - { os: "ubuntu-24.04", cc: "gcc-13",   cxx: "g++-13" }
        - { os: "ubuntu-24.04", cc: "clang-19", cxx: "clang++-19" }
        
        backend: ["MML", "SDL", "GLFW"]
    #name: "${{matrix.config.cxx}}"
    steps:
    - name: Setup
      run: |
        sudo apt-get update -o Acquire::Retries=10
        sudo apt-get install -o Acquire::Retries=10 -y cmake ninja-build ${{matrix.config.cc}} ${{matrix.config.cxx}}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get install libgtk-3-dev
        sudo apt-get install libudev-dev
    - name: Build
      run: |
        cmake --preset linux-${{matrix.config.cc}} -DOSPP_BACKEND_TYPE=${{matrix.backend}}
        cmake --build --preset linux-${{matrix.config.cc}}-release
